language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  
before_script:
  - sudo apt-get --yes --force-yes update
  - sudo apt-get --yes --force-yes install python-software-properties
  - sudo add-apt-repository --y ppa:webupd8team/java
  - sudo apt-get --yes --force-yes update
  - sudo apt-get --yes --force-yes install mysql-server
  - sudo apt-get --yes --force-yes install oracle-java7-installer
  - wget download.java.net/glassfish/4.0/release/glassfish-4.0.zip
  - sudo apt-get --yes --force-yes install unzip
  - sudo unzip glassfish-4.0.zip -d /opt
  - export CLASSPATH=lib/junit-4.11.jar:lib/hamcrest-core-1.3.jar:lib/json-simple-1.1.1.jar:src/:bin/:lib/
  - export PATH=/opt/glassfish4/bin/:$PATH
  - sudo chmod +x /opt/glassfish4/bin/asadmin
  - cd /opt/glassfish4/bin/
  - sudo ./asadmin start-domain
  - cd
  - pwd
  - cd build/ivxn2309/HospitAppServer
  - mysql -e 'source HospitAppDB.sql;' -uroot
  - mkdir bin  
 
  
script:
  - javac -cp .:lib/junit-4.11.jar:lib/hamcrest-core-1.3.jar:lib/json-simple-1.1.1.jar -d bin src/java/test/ScheduleManagerTest.java
  - sudo cp dist/HospitAppServer.war /opt/glassfish4/glassfish/domains/domain1/autodeploy/
  - java org.junit.runner.JUnitCore test.ScheduleManagerTest
  - mysql -e 'source HospitAppDBTest.sql;' -uroot