language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  
before_script:
  - ls -l
  - ls -l ../
  - ls -l ../../
  - ls -l ../../../
  - sudo apt-get --yes --force-yes update
  - sudo apt-get --yes --force-yes install python-software-properties
  - sudo add-apt-repository --y ppa:webupd8team/java
  - sudo apt-get --yes --force-yes update
  - sudo apt-get --yes --force-yes install oracle-java7-installer
  - wget download.java.net/glassfish/4.0/release/glassfish-4.0.zip
  - sudo apt-get --yes --force-yes install unzip
  - sudo unzip glassfish-4.0.zip -d /opt
  - export CLASSPATH=lib/junit-4.11.jar:lib/hamcrest-core-1.3.jar:src/:bin/
  - export PATH=/opt/glassfish4/bin/:$PATH
  - sudo chmod +x /opt/glassfish4/bin/asadmin
  - cd /opt/glassfish4/bin/
  - sudo ./asadmin start-domain
  - cd
  - cd build/ivxn2309/HospitAppServer
  
  
script:
  - ls -l
  - javac -d bin src/java/multixsoft/hospitapp/unittest/ScheduleManagerTest.java
  - java org.junit.runner.JUnitCore multixsoft.hospitapp.unittest.ScheduleManagerTest