language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  
before_script:
  - mkdir build
  - sudo apt-get --yes --force-yes update
  - sudo apt-get --yes --force-yes install python-software-properties
  - sudo add-apt-repository --yes --force-yes ppa:webupd8team/java
  - sudo apt-get --yes --force-yes update
  - sudo apt-get --yes --force-yes install oracle-java7-installer
  - wget download.java.net/glassfish/4.0/release/glassfish-4.0.zip
  - apt-get --yes --force-yes install unzip
  - unzip glassfish-4.0.zip -d /opt
  - export CLASSPATH=lib/junit-4.11.jar:lib/hamcrest-core-1.3.jar:src/:bin/:/opt/glassfish4/bin:$PATH
  - asadmin start-domain
  
script:
  - javac -d bin src/java/multixsoft/hospitapp/unittest/ScheduleManagerTest.java
  - java org.junit.runner.JUnitCore multixsoft.hospitapp.unittest.ScheduleManagerTest