language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  
before_script:
  - mkdir bin
  - export CLASSPATH=lib/junit-4.11.jar:lib/hamcrest-core-1.3.jar:src/:bin/
  - ls
  
script:
  - javac -d bin src/java/multixsoft/hospitapp/unittest/ScheduleManageTest.java
  - java org.junit.runner.JUnitCore multixsoft.hospitapp.unittest.ScheduleManageTest